### ISSUE TITLE
训练出来的效果怎么样

### ISSUE THREAD

**Issue by a767421378** [yigeyouzia/FpsCheat-yolo#4]
移动鼠标可以用硬件解决 这个我测试过了 不过我用自动扳机效果不太好 感觉是找色的问题 我想试试yolo效果怎么样 有V吗加一下

**Comment by yigeyouzia** [comment]
你留你的我加你

**Comment by yigeyouzia** [comment]
> 移动鼠标可以用硬件解决 这个我测试过了 不过我用自动扳机效果不太好 感觉是找色的问题 我想试试yolo效果怎么样 有V吗加一下

你留你的我加你

**Comment by a767421378** [comment]
zeus773503118
